backend:
    name: github
    repo: tylerlangties/gatsbynetlify

media_folder: static/assets

collections: 
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }